name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 7 * * */2'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
# See https://github.com/easimon/maximize-build-space/blob/master/action.yml
      - name: Try to free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc
# /usr/share/dotnet can also be removed if it's clear that it isn't needed by any actions

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10.22.0

      - uses: actions/checkout@v2.3.4
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)

      - name: Checkout submodules
        run: |
          git submodule update --init --depth 1 -j 4 themes/*
          for dir in `ls blogs/`; do echo "Checking out submodule blogs/$dir" ; git submodule update --depth 1 -j 4 --init blogs/$dir ; rm -rf blogs/$dir/.git ; find blogs/$dir -type f -size +1M -name '*.jpg' -print -exec rm {} \;  ; done
#          ./scripts/git-checkout.sh

      - name: Install required dependencies
        run: |
          ./themes/projektemacher-base/scripts/github/setup-dependendies.sh
          ./themes/projektemacher-base/scripts/github/docker-images.sh

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Create IIIF derivates
        run: |
          docker run -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.81.0'
          extended: true
      - name: Build Hugo site
        run: hugo --i18n-warnings

      - name: Index and cleanup
        run: |
          ./scripts/post-build.sh

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
