name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '30 3 * * */1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUGO_VERSION: 0.133.0

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
#      - name: Maximize build space
#        uses: easimon/maximize-build-space@master
#        with:
#          root-reserve-mb: 4096
#          temp-reserve-mb: 1096
#          remove-android: 'true'
#          remove-haskell: 'true'
#          remove-codeql: 'true'
#          remove-dotnet: 'true'

      - name: Free some disk space
        run: |
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' '^postgresql-.*' '^gfortran-.*' '^cmake-.*' '^aspnetcore-.*' '^libmono-.*' '^mono-.*' '^ruby.*' '^r-.*' azure-cli powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - uses: actions/checkout@v4
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)

      - name: Checkout submodules
        run: |
          git submodule update --init --depth 1 -j 4 themes/*
          for dir in `ls blogs/`; do echo "Checking out submodule blogs/$dir" ; git submodule update --depth 1 -j 4 --init blogs/$dir ; rm -rf blogs/$dir/.git ; find blogs/$dir -type f -size +1M \( -name '*.jpg' -o -name '*.jxl' \) -print -exec rm {} \;  ; done
#          ./scripts/git-checkout.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          ./scripts/github-setup.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'

      - name: Setup yarn
        run: npm install -g yarn

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Create IIIF derivates
        run: |
          docker run -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest-jxl-uploader sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Generate stats
        run: |
          ./themes/projektemacher-base/scripts/stat.sh

      - name: Build Hugo site
        run: hugo --printI18nWarnings --printUnusedTemplates

      - name: Index and cleanup
        run: |
          ./scripts/post-build.sh

      - name: Puppeteer
        run: ./themes/projektemacher-base/scripts/github/check-js-errors.sh

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
