name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 7 * * */2'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get install git libtiff5 imagemagick

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)

      - name: Create IIIF derivates
        run: |
          ls content/logo
          ls content/logo/img001.jpg
          docker run -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: Checkout submodules
        run: |
          git submodule update --init --depth 1 -j 4 themes/*
          for dir in `ls blogs/`; do echo "Checking out submodule blogs/$dir" ; git submodule update --depth 1 -j 4 --init blogs/$dir ; find blogs/$dir -type f -size +1M -name '*.jpg' -print -exec rm {} \;  ; done

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true
      - name: Build Hugo site
        run: hugo

      - name: Index and cleanup
        run: |
          ./scripts/post-build.sh

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
