name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Imagemagick
        run: |
          sudo apt-get install libtiff5 imagemagick

      - name: Convert source file
        run: |
          convert "Source Files/Logo/img001-color.jpg" -crop 5324x3260+0+90 content/logo/img001.jpg

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install iiif
      - name: Generate Tiles
        run: |
          cd content/logo
          iiif_static.py -d . img001.jpg

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0
      - name: Install Node dependencies
        run: |
          yarn install
          yarn run svgo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true
      - name: Build Hugo site
        run: hugo

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
